version: '3.8'

services:
  dbservice:
    image: postgres:latest
    command: ["postgres"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - grocerystoreprojectnw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d grocery-store -h localhost"]
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s

  appservice:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      dbservice:
        condition: service_healthy
    environment:
      POSTGRES_DB: grocery-store
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbservice:5432/grocery-store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 9090:9090
    networks:
      - grocerystoreprojectnw

networks:
  grocerystoreprojectnw:
